# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: example_password
    salt: "generateme"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  trellis.code.fv.de:
    env:
      db_password: example_dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "(@%L#,BaM]P(kfG)%7./_Ka![l{6A@HjgiKVe{M`mA;GA:{Ph0HhpA|bo-)ccz+!"
      secure_auth_key: "EiYp,_(@LD}rjc<Y:P@0mJ6.S#?{b==W-f.E7t*`VC:fQFmX-+n2tsElSDA@A^Iz"
      logged_in_key: "^?IyY$HAdW3Ey1YET>jKkaGzk%iZ|RAj`V7Rn:Y67i$)B)e0*_gKRca..0rJ7=ol"
      nonce_key: "vwP(p0.C1O]IDuF,gg2dSfOOpf%iCSHY&OtAUY1C!Ft>Sq8}`iDCxKk+Z$[x/WZJ"
      auth_salt: "EvX0qNQ:FlvSE]h7#(tJ,!K$3xS],fdgtkVnq>0u9xmLB+Yo*aEA492V`__z!c^U"
      secure_auth_salt: "!WLl<Um6!35&Noo`SH89>x*_>0<Ck/My}x7!QbK5r8J*8fOAkY+c&QqjXYm_$t(K"
      logged_in_salt: "/]Abj{VZCFd<Rhryop8uLN#k})?,2T?mASt=nH?QBF@B1zFtB^Adp?K!t2w,{fQ?"
      nonce_salt: "t-?s!<-I^ZW,]4yWYP-O!=J{:-qx,-3LGel7kaEhpi&YDi?aUfRs;/kr2yj}bZ-A"
